"""Name unique

Revision ID: 8568e96061db
Revises: d4363e16db32
Create Date: 2023-03-03 13:40:23.749747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8568e96061db'
down_revision = 'd4363e16db32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheese_type', schema=None) as batch_op:
        batch_op.create_unique_constraint("cheese_type_unique_name", ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheese_type', schema=None) as batch_op:
        batch_op.drop_constraint("cheese_type_unique_name", type_='unique')

    # ### end Alembic commands ###
